# NumPy Exercises

아웃풋과 같은 결과를 만들어내면 됩니다. 랜덤 넘버 생성의 경우, 대충 비슷하면 됩니다.

#### numpy 라이브러리를 np로 임포트

#### 10개의 0을 가진 array를 생성하기

In [2]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 10개의 1을 가진 array 생성하기

In [3]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### 10개의 5를 가진 array 생성하기

In [4]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### 10부터 50까지 정수를 포함한 array 생성하기

In [5]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 10부터 50까지 짝수만 포함한 array 생성하기

In [6]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 0부터 8까지 포함한 3x3 행렬 생성하기

In [7]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 3x3 identity matrix 생성하기

In [8]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 0부터 1 사이의 random number 1개로 구성된 array 생성하기

In [15]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([ 0.42829726])

#### standard normal로부터 25개의 숫자로 구성된 array 생성하기

In [33]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### 다음처럼 생긴 행렬 생성하기

In [35]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

## Numpy Indexing and Selection

이 셀은 수정 금지

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

`mat` 행렬로부터 다음 출력값을 인덱싱을 통해 얻어내기

In [40]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

`mat` 행렬로부터 다음 출력값을 인덱싱을 통해 얻어내기

In [41]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

20

`mat` 행렬로부터 다음 출력값을 인덱싱을 통해 얻어내기

In [42]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[ 2],
       [ 7],
       [12]])

`mat` 행렬로부터 다음 출력값을 인덱싱을 통해 얻어내기

In [46]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([21, 22, 23, 24, 25])

`mat` 행렬로부터 다음 출력값을 인덱싱을 통해 얻어내기

In [49]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 기타

#### `mat`행렬의 모든 원소의 합

In [50]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

325

#### `mat`행렬의 모든 원소의 표준편차

In [51]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

7.2111025509279782

#### `mat`행렬에서 각 column별로 원소의 합

In [53]:
# 이 셀은 실행하지 마세요. 출력이 사라집니다.

array([55, 60, 65, 70, 75])